### ISSUE TITLE
Only getting non-explicit search results

### ISSUE THREAD

**Issue by codeblech** [CatchZeng/bing_images#4]
By default, the module seems to only respond with non-explicit search results _(SafeSearch: moderate)._
Is there a way to change this to _SafeSearch: off_ ?

**Comment by CatchZeng** [comment]
SafeSearch is a setting item of bing.com, which does not belong to the scope of bing_images module. 

See more at https://support.microsoft.com/en-us/topic/turn-bing-safesearch-on-or-off-446ebfb8-becf-f035-9eea-b660e8420458

**Comment by codeblech** [comment]
I saw that feature in this related module,
https://github.com/gurugaurav/bing_image_downloader

**Comment by CatchZeng** [comment]
You can upgrade bing_image to 0.2.2 and try `extra_query_params`.

```py
from bing_images import bing

urls = bing.fetch_image_urls("cat", 
limit=10, 
file_type='png',
filters='+filterui:aspect-square+filterui:color2-bw', 
extra_query_params='&adlt=off')
print("{} images.".format(len(urls)))
counter = 1
for url in urls:
    print("{}: {}".format(counter, url))
    counter += 1
```
